global:
  scrape_interval: 15s

# enable lifecycle api


scrape_configs:
  - job_name: 'backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'redis'
    scrape_interval: 5s
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'coredns'
    dns_sd_configs:
      - names:
        - '*'
        type: 'A'
        port: 53
